// 1. Import Area
// import defaultimport  from 'somelibarary/location';
import Head from 'next/head'
import styles from '../styles/Home.module.css'
import A from '../components/A';



// 2. Defination Area
 function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <A name="Anil" mag="OKLABS" sir=" Sir : Check my Code"></A>
     
    </div>
  )
}
// Export Area
export default Home ;
